### ISSUE TITLE
when i pip install git+https://github.com/tatsy/torchmcubes.git  I have a problem

### ISSUE THREAD

**Issue by guahunyo** [flowtyone/ComfyUI-Flowty-TripoSR#4] opened 2024-03-05 15:09 UTC
![image](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/18573180/19cbf22b-d298-462d-b91c-c530f29a38a0)

**Comment by flowtyone** [comment] 2024-03-05 15:17
Duplicate of https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/issues/1

**Closed** 2024-03-05 15:17 UTC
