### ISSUE TITLE
Could not build wheels for torchmcubes (Win11)

### ISSUE THREAD

**Issue by rethink-studios** [flowtyone/ComfyUI-Flowty-TripoSR#6] opened 2024-03-05 15:43 UTC
Installed via git clone and pip install -r requirements.txt
(Apologies, I stripped my path names to hard drives)

(base) <myPATH>ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR>pip install -r requirements.txt
Collecting git+https://github.com/tatsy/torchmcubes.git (from -r requirements.txt (line 4))
  Cloning https://github.com/tatsy/torchmcubes.git to <myPATH>\appdata\local\temp\pip-req-build-7hyy5mj7
  Running command git clone --filter=blob:none --quiet https://github.com/tatsy/torchmcubes.git '<myPATH>\AppData\Local\Temp\pip-req-build-7hyy5mj7'
  Resolved https://github.com/tatsy/torchmcubes.git to commit 3aef8afa5f21b113afc4f4ea148baee850cbd472
  Preparing metadata (setup.py) ... done
Requirement already satisfied: omegaconf==2.3.0 in <myPATH>\anaconda3\lib\site-packages (from -r requirements.txt (line 1)) (2.3.0)
Collecting Pillow==10.1.0 (from -r requirements.txt (line 2))
  Downloading Pillow-10.1.0-cp39-cp39-win_amd64.whl.metadata (9.6 kB)
Collecting einops==0.7.0 (from -r requirements.txt (line 3))
  Using cached einops-0.7.0-py3-none-any.whl.metadata (13 kB)
Collecting transformers==4.35.0 (from -r requirements.txt (line 5))
  Downloading transformers-4.35.0-py3-none-any.whl.metadata (123 kB)
     ---------------------------------------- 123.1/123.1 kB 2.4 MB/s eta 0:00:00
Collecting trimesh==4.0.5 (from -r requirements.txt (line 6))
  Downloading trimesh-4.0.5-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: huggingface-hub in <myPATH>\anaconda3\lib\site-packages (from -r requirements.txt (line 7)) (0.20.3)
Requirement already satisfied: imageio[ffmpeg] in <myPATH>\anaconda3\lib\site-packages (from -r requirements.txt (line 8)) (2.19.3)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in <myPATH>\anaconda3\lib\site-packages (from omegaconf==2.3.0->-r requirements.txt (line 1)) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in <myPATH>\anaconda3\lib\site-packages (from omegaconf==2.3.0->-r requirements.txt (line 1)) (6.0)
Requirement already satisfied: filelock in <myPATH>\anaconda3\lib\site-packages (from transformers==4.35.0->-r requirements.txt (line 5)) (3.6.0)
Requirement already satisfied: numpy>=1.17 in <myPATH>\anaconda3\lib\site-packages (from transformers==4.35.0->-r requirements.txt (line 5)) (1.23.5)
Requirement already satisfied: packaging>=20.0 in <myPATH>\anaconda3\lib\site-packages (from transformers==4.35.0->-r requirements.txt (line 5)) (21.3)
Requirement already satisfied: regex!=2019.12.17 in <myPATH>\anaconda3\lib\site-packages (from transformers==4.35.0->-r requirements.txt (line 5)) (2022.7.9)
Requirement already satisfied: requests in <myPATH>\anaconda3\lib\site-packages (from transformers==4.35.0->-r requirements.txt (line 5)) (2.28.1)
Collecting tokenizers<0.15,>=0.14 (from transformers==4.35.0->-r requirements.txt (line 5))
  Downloading tokenizers-0.14.1-cp39-none-win_amd64.whl.metadata (6.8 kB)
Requirement already satisfied: safetensors>=0.3.1 in <myPATH>\anaconda3\lib\site-packages (from transformers==4.35.0->-r requirements.txt (line 5)) (0.4.2)
Requirement already satisfied: tqdm>=4.27 in <myPATH>\anaconda3\lib\site-packages (from transformers==4.35.0->-r requirements.txt (line 5)) (4.64.1)
Requirement already satisfied: fsspec>=2023.5.0 in <myPATH>\anaconda3\lib\site-packages (from huggingface-hub->-r requirements.txt (line 7)) (2024.2.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in <myPATH>\anaconda3\lib\site-packages (from huggingface-hub->-r requirements.txt (line 7)) (4.3.0)
Requirement already satisfied: imageio-ffmpeg in <myPATH>\anaconda3\lib\site-packages (from imageio[ffmpeg]->-r requirements.txt (line 8)) (0.4.9)
Requirement already satisfied: psutil in <myPATH>\anaconda3\lib\site-packages (from imageio[ffmpeg]->-r requirements.txt (line 8)) (5.9.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in <myPATH>\anaconda3\lib\site-packages (from packaging>=20.0->transformers==4.35.0->-r requirements.txt (line 5)) (3.0.9)
Collecting huggingface-hub (from -r requirements.txt (line 7))
  Downloading huggingface_hub-0.17.3-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: colorama in <myPATH>\anaconda3\lib\site-packages (from tqdm>=4.27->transformers==4.35.0->-r requirements.txt (line 5)) (0.4.5)
Requirement already satisfied: setuptools in <myPATH>\anaconda3\lib\site-packages (from imageio-ffmpeg->imageio[ffmpeg]->-r requirements.txt (line 8)) (63.4.1)
Requirement already satisfied: charset-normalizer<3,>=2 in <myPATH>\anaconda3\lib\site-packages (from requests->transformers==4.35.0->-r requirements.txt (line 5)) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in <myPATH>\anaconda3\lib\site-packages (from requests->transformers==4.35.0->-r requirements.txt (line 5)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in <myPATH>\anaconda3\lib\site-packages (from requests->transformers==4.35.0->-r requirements.txt (line 5)) (1.26.11)
Requirement already satisfied: certifi>=2017.4.17 in <myPATH>\anaconda3\lib\site-packages (from requests->transformers==4.35.0->-r requirements.txt (line 5)) (2023.5.7)
Downloading Pillow-10.1.0-cp39-cp39-win_amd64.whl (2.6 MB)
   ---------------------------------------- 2.6/2.6 MB 7.2 MB/s eta 0:00:00
Using cached einops-0.7.0-py3-none-any.whl (44 kB)
Downloading transformers-4.35.0-py3-none-any.whl (7.9 MB)
   ---------------------------------------- 7.9/7.9 MB 9.4 MB/s eta 0:00:00
Downloading trimesh-4.0.5-py3-none-any.whl (688 kB)
   ---------------------------------------- 688.5/688.5 kB 8.7 MB/s eta 0:00:00
Downloading tokenizers-0.14.1-cp39-none-win_amd64.whl (2.2 MB)
   ---------------------------------------- 2.2/2.2 MB 8.7 MB/s eta 0:00:00
Downloading huggingface_hub-0.17.3-py3-none-any.whl (295 kB)
   ---------------------------------------- 295.0/295.0 kB 9.2 MB/s eta 0:00:00
Building wheels for collected packages: torchmcubes
  Building wheel for torchmcubes (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  ¦ exit code: 1
  ?-> [14 lines of output]
      CUDA environment was not successfully loaded!
      Build only CPU module!
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\torchmcubes
      copying torchmcubes\__init__.py -> build\lib.win-amd64-cpython-39\torchmcubes
      running build_ext
      <myPATH>\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'torchmcubes_module' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torchmcubes
  Running setup.py clean for torchmcubes
Failed to build torchmcubes
ERROR: Could not build wheels for torchmcubes, which is required to install pyproject.toml-based projects

(base) <myPATH>\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR>

**Comment by Ratinod** [comment] 2024-03-05 18:21
As always happens, build is works most likely only for Linux.
And at https://www.lfd.uci.edu/~gohlke/pythonlibs/ there is no ready-made torchmcubes.whl file...

**Comment by Ratinod** [comment] 2024-03-05 18:46
There are always problems with this "wheels". Maybe there are ready-made .whl files somewhere?
I couldn't find it. I only found that torchmcubes has been removed from PyPi (https://libraries.io/pypi/torchmcubes) and can no longer be installed using pip install.

**Comment by flowtyone** [comment] 2024-03-05 19:36
duplicate of https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/issues/1

**Closed by flowtyone** 2024-03-05 19:36 UTC
