### ISSUE TITLE
Cannot import D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR module for custom nodes: cannot import name 'marching_cubes' from 'torchmcubes' (unknown location)

### ISSUE THREAD

**Issue by azazeal04** [flowtyone/ComfyUI-Flowty-TripoSR#5] opened 2024-03-05 15:32 UTC
After installing the custom node and gone through the entire setup process and installed TorchMCubes I get this error Cannot import D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR module for custom nodes: cannot import name 'marching_cubes' from 'torchmcubes' (unknown location)

**Comment by fogostudio** [comment] 2024-03-05 16:22
Seconded, I have the same error:

`Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR\__init__.py", line 6, in <module>
    from tsr.system import TSR
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR\tsr\system.py", line 16, in <module>
    from .models.isosurface import MarchingCubeHelper
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR\tsr\models\isosurface.py", line 6, in <module>
    from torchmcubes import marching_cubes
ModuleNotFoundError: No module named 'torchmcubes'`

**Comment by jloveric** [comment] 2024-03-05 17:31
On ubuntu, I'm seeing the following error AttributeError: module 'torchmcubes_module' has no attribute 'mcubes_cuda'

**Comment by flowtyone** [comment] 2024-03-05 19:36
duplicate of https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/issues/1

**Closed by flowtyone** 2024-03-05 19:36 UTC

**Comment by azazeal04** [comment] 2024-03-05 19:43
This is not even close to the problem you linked to. They dont find module named torch in their report, my problem is it dont find the  'marching_cubes' from 'torchmcubes' so definitely a completely different error.

**Comment by flowtyone** [comment] 2024-03-05 19:49
> This is not even close to the problem you linked to. They dont find module named torch in their report, my problem is it dont find the 'marching_cubes' from 'torchmcubes' so definitely a completely different error.

All of these errors were caused by the torchmcubes module, so I want just one issue where I can update for potential fixes.

**Comment by Kyxsune** [comment] 2024-03-05 20:29
Just adding on that the solution found in this thread worked for me.

https://github.com/VAST-AI-Research/TripoSR/issues/3#issuecomment-1978104374
