### ISSUE TITLE
The TripoSR viewer dont show the Mesh

### ISSUE THREAD

**Issue by kakachiex2** [flowtyone/ComfyUI-Flowty-TripoSR#18] opened 2024-03-06 17:26 UTC
No mesh in the 3d viewer I test inverting the mask and normal mask but keep black I update the extension and the same problem.
 
![Screenshot 2024-03-06 132458](https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/assets/1762112/613af660-2173-4f86-a956-f09aae7c214a)

**Comment by flowtyone** [comment] 2024-03-07 05:48
Can you check the browser developer tools for errors?

**Comment by flowtyone** [comment] 2024-03-07 05:50
Duplicate of https://github.com/flowtyone/ComfyUI-Flowty-TripoSR/issues/17 , please follow there

**Closed** 2024-03-07 05:50 UTC
